---
title: "Puntos"
author: "Irene Ponce Huerta"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Corrige Data Camp

## Corrección de las entregas de Data Camp


```{r}
#Cargar las librerias
library(dplyr)
library(stringr)
library(readxl)
library(writexl)
```

```{r}
#Ponemos la ruta directamente porque ya esta descomprimido
ruta <- "~/Desktop/universidad/tratamiento de datos/CorrigeDataCamp/2025-26 Tractament de les dades Gr.A-T (36423)-Tarea Intermediate R(Datacamp)-3281647"

#Usamos list.files para sacar los archivos txt que son de texto y los de pdf que son los certificados

ficheros_puntos <- list.files(ruta, pattern = "\\.txt$", recursive = TRUE, full.names = TRUE)
ficheros_certificados <- list.files(ruta, pattern = "\\.pdf$", recursive = TRUE, full.names = TRUE)


#Para ver cuantas variantes de los nombres de puntos.txt
nombres_puntos <- basename(ficheros_puntos)
variantes_puntos <- unique(nombres_puntos)

print("Variantes de nombres encontradas:") ;print(variantes_puntos)

print("Número de variantes:") ;print(length(variantes_puntos))

print("¿Todos se llaman puntos.txt?:") ; print(identical(variantes_puntos, "puntos.txt"))


#Hacemos un bucle para hacer un df con los apellidos del usuario,la puntuación obtenida, el nombre del fichero usado para almacenar los puntos y el contenido del fichero puntos.txt como cadena de texto.
apellidos_vec <- c()
puntos_vec <- c()
NomFile_vec <- c()
Puntos_vec <- c()

for (i in 1:length(ficheros_puntos)) {
  ruta_archivo <- ficheros_puntos[i]
  
  #Usamos strsplit para extraer el apellido de la ruta
  
  partes_ruta <- unlist(strsplit(ruta_archivo, "/"))
  carpeta_alumno <- partes_ruta[length(partes_ruta) - 1]
  
  #Nos quedamos con el nombre solo
  nombre_completo <- strsplit(carpeta_alumno, "_")[[1]][1]
  
  #Cogemos los apellidos
  apellido_limpio <- strsplit(nombre_completo, ",")[[1]][1]
  
  #Quitamos espacios
  apellido_limpio <- gsub("^\\s+|\\s+$", "", apellido_limpio)
  apellido_limpio <- gsub("\\s+", " ", apellido_limpio)
  
  #Leemos y lo unimos todo
  contenido <- readLines(ruta_archivo, warn = FALSE)
  contenido_texto <- paste(contenido, collapse = " ")
  
  #Sacamos los numeros
  numero <- as.numeric(gsub("[^0-9]", "", contenido_texto))
  
  #Guardamos en los vectores creados al principio
  apellidos_vec <- c(apellidos_vec, apellido_limpio)
  puntos_vec <- c(puntos_vec, numero)
  NomFile_vec <- c(NomFile_vec, basename(ruta_archivo))
  Puntos_vec <- c(Puntos_vec, contenido_texto)
}

```

